baseurl = "https://www.eddatadoneright.com/"
languageCode = "en-us"
title = "Education Data Done Right"
theme = "timer-hugo"
googleAnalytics = "UA-53342829-3"
# disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

#[[menu.main]]
 #   name = "About"
#    url = "/about/"
#[[menu.main]]
#    name = "Authors"
#    url = "/authors/"
#[[menu.main]]
#    name = "Contributors"
#    url = "/contributors/"

[menu]
    [[menu.nav]]
        name = "About"
        url = "/about/"
        tags = false
    [[menu.nav]]
        name = "Authors"
        url = "/authors/"
        tags = false
    [[menu.nav]]
        name = "Contributors"
        url = "/contributors/"
        tags = false
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog/"
        weight  = 5


[params]
    home = "Home"
    description = "Education Data Done Right: A View from the Trenches."
    title   = "Education Data Done Right"
    tags = false
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    # path to the favicon, under "static"
    favicon = "favicon.ico"
    logo = "logo.png"


[params.banner]
    enable = true
    bgImage ="banner_tall2.jpg"
  #heading = "banner_test.jpg"

[params.about]
        enable  = false

[params.cta]
    enable = false


[params.portfolio]
    enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
