---
title: Data Ops and Education Data
author: Wendy Geller
date: '2019-12-16'
slug: data-ops
categories: []
tags: []
---


Wendy recently published a blog post for the State of Vermont Agency of Education on a vision 
for data infrastructure for the future. In the post, Wendy identifies systemic data challenges 
education agencies face, the benefits of addressing them correctly, and lays out a roadmap for 
meeting those challenges in an inclusive, thoughtful, and systematic way. 


> On balance, infrastructure isn’t something that organizations regularly focus on, though, unless there’s something very wrong with those systems that’s apparent and frustrating to everyone. But, even then, it’s not a given that resources will be deployed to address those challenges quickly.

> If we want to be data-driven organizations, if we want to have the information we need on hand when we must take important decisions, if we want to be able to leverage data to support improved outcomes for kids, then it’s time to deploy those resources. It’s time to pay attention to data infrastructure.

[Head over to the blog and read her post about Data Ops to learn more!](https://education.vermont.gov/leadership-blog/freedom-and-unity-tackling-data-challenges-together)